ipkg-build from LEDE

diff --git a/ipkg-build b/ipkg-build
--- a/ipkg-build
+++ b/ipkg-build
@@ -3,7 +3,32 @@
 # ipkg-build -- construct a .ipk from a directory
 # Carl Worth <cworth@east.isi.edu>
 # based on a script by Steve Redler IV, steve@sr-tech.com 5-21-2001
+# 2003-04-25 rea@sr.unh.edu
+#   Updated to work on Familiar Pre0.7rc1, with busybox tar.
+#   Note it Requires: binutils-ar (since the busybox ar can't create)
+#   For UID debugging it needs a better "find".
 set -e
+
+version=1.0
+FIND="$(which find)"
+FIND="${FIND:-$(which gfind)}"
+TAR="${TAR:-$(which tar)}"
+GZIP="$(which gzip)"
+
+# try to use fixed source epoch
+if [ -n "$SOURCE_DATE_EPOCH" ]; then
+	TIMESTAMP=$(date --date="@$SOURCE_DATE_EPOCH")
+
+	# look up date of last commit
+elif [ -d "$TOPDIR/.git" ]; then
+	GIT="$(which git)"
+	TIMESTAMP=$(cd $TOPDIR; $GIT log -1 -s --format=%ci)
+elif [ -d "$TOPDIR/.svn" ]; then
+	SVN="$(which svn)"
+	TIMESTAMP=$($SVN info "$TOPDIR" | sed -n "s/^Last Changed Date: \(.*\)/\1/p")
+else
+	TIMESTAMP=$(date)
+fi
 
 ipkg_extract_value() {
 	sed -e "s/^[^:]*:[[:space:]]*//"
@@ -12,61 +37,37 @@ ipkg_extract_value() {
 required_field() {
 	field=$1
 
-	value=`grep "^$field:" < $CONTROL/control | ipkg_extract_value`
-	if [ -z "$value" ]; then
-		echo "ipkg-build: Error: $CONTROL/control is missing field $field" ;
-		PKG_ERROR=1
-	fi
-	echo $value
+	grep "^$field:" < $CONTROL/control | ipkg_extract_value
 }
 
 pkg_appears_sane() {
 	local pkg_dir=$1
 
-	local owd=`pwd`
+	local owd=$PWD
 	cd $pkg_dir
 
 	PKG_ERROR=0
-	if [ ! -f "$CONTROL/control" ]; then
-		echo "ipkg-build: Error: Control file $pkg_dir/$CONTROL/control not found."
-		cd $owd
-		return 1
-	fi
-
 	pkg=`required_field Package`
-	version=`required_field Version`
+	version=`required_field Version | sed 's/Version://; s/^.://g;'`
 	arch=`required_field Architecture`
-	required_field Maintainer >/dev/null
-	required_field Description >/dev/null
 
-	if echo $pkg | grep '[^a-z0-9.+-]'; then
-		echo "ipkg-build: Error: Package name $name contains illegal characters, (other than [a-z0-9.+-])"
+	if echo $pkg | grep '[^a-zA-Z0-9_.+-]'; then
+		echo "*** Error: Package name $name contains illegal characters, (other than [a-z0-9.+-])" >&2
 		PKG_ERROR=1;
 	fi
 
-	local bad_fields=`sed -ne 's/^\([^[:space:]][^:[:space:]]\+[[:space:]]\+\)[^:].*/\1/p' < $CONTROL/control | sed -e 's/\\n//'`
-	if [ -n "$bad_fields" ]; then
-		bad_fields=`echo $bad_fields`
-		echo "ipkg-build: Error: The following fields in $CONTROL/control are missing a ':'"
-		echo "	$bad_fields"
-		echo "ipkg-build: This may be due to a missing initial space for a multi-line field value"
-		PKG_ERROR=1
-	fi
-
-	for script in $CONTROL/preinst $CONTROL/postinst $CONTROL/prerm $CONTROL/postrm; do
-		if [ -f $script -a ! -x $script ]; then
-			echo "ipkg-build: Error: package script $script is not executable"
-			PKG_ERROR=1
-		fi
-	done
-
 	if [ -f $CONTROL/conffiles ]; then
-		for cf in `cat $CONTROL/conffiles`; do
-			if [ ! -f ./$cf ]; then
-				echo "ipkg-build: Error: $CONTROL/conffiles mentions conffile $cf which does not exist"
-				PKG_ERROR=1
-			fi
+		rm -f $CONTROL/conffiles.resolved
+
+		for cf in `$FIND $(sed -e "s!^/!$pkg_dir/!" $CONTROL/conffiles) -type f`; do
+			echo "${cf#$pkg_dir}" >> $CONTROL/conffiles.resolved
 		done
+
+		rm $CONTROL/conffiles
+		if [ -f $CONTROL/conffiles.resolved ]; then
+			mv $CONTROL/conffiles.resolved $CONTROL/conffiles
+			chmod 0644 $CONTROL/conffiles
+		fi
 	fi
 
 	cd $owd
@@ -76,51 +77,89 @@ pkg_appears_sane() {
 ###
 # ipkg-build "main"
 ###
+ogargs=""
+noclean=0
+usage="Usage: $0 [-c] [-C] [-o owner] [-g group] <pkg_directory> [<destination_directory>]"
+while getopts "cg:ho:v" opt; do
+	case $opt in
+		o ) owner=$OPTARG
+			ogargs="--owner=$owner"
+			;;
+		g ) group=$OPTARG
+			ogargs="$ogargs --group=$group"
+			;;
+		c ) ;;
+		C ) noclean=1;;
+		v ) echo $version
+			exit 0
+			;;
+		h ) echo $usage  >&2 ;;
+		\? ) echo $usage  >&2
+	esac
+done
+
+
+shift $(($OPTIND - 1))
+
+# continue on to process additional arguments
 
 case $# in
-1)
-	dest_dir=.
-	;;
-2)
-	dest_dir=$2
-	;;
-*)
-	echo "Usage: ipkg-build <pkg_directory> [<destination_directory>]" ;
-	exit 1 
-	;;
+	1)
+		dest_dir=$PWD
+		;;
+	2)
+		dest_dir=$2
+		if [ "$dest_dir" = "." -o "$dest_dir" = "./" ] ; then
+			dest_dir=$PWD
+		fi
+		;;
+	*)
+		echo $usage >&2
+		exit 1
+		;;
 esac
 
 pkg_dir=$1
 
 if [ ! -d $pkg_dir ]; then
-	echo "ipkg-build: Error: Directory $pkg_dir does not exist"
+	echo "*** Error: Directory $pkg_dir does not exist" >&2
 	exit 1
 fi
 
 # CONTROL is second so that it takes precedence
 CONTROL=
-[ -d $pkg_dir/DEBIAN ] && CONTROL=DEBIAN
 [ -d $pkg_dir/CONTROL ] && CONTROL=CONTROL
 if [ -z "$CONTROL" ]; then
-	echo "ipkg-build: Error: Directory $pkg_dir has no CONTROL subdirectory."
+	echo "*** Error: Directory $pkg_dir has no CONTROL subdirectory." >&2
 	exit 1
 fi
 
 if ! pkg_appears_sane $pkg_dir; then
-	echo "Please fix the above errors and try again."
+	echo >&2
+	echo "ipkg-build: Please fix the above errors and try again." >&2
 	exit 1
 fi
 
 tmp_dir=$dest_dir/IPKG_BUILD.$$
 mkdir $tmp_dir
 
-tar -C $pkg_dir -czf $tmp_dir/data.tar.gz . --exclude=$CONTROL
-tar -C $pkg_dir/$CONTROL -czf $tmp_dir/control.tar.gz .
+echo $CONTROL > $tmp_dir/tarX
+# Preserve permissions (-p) when creating data.tar.gz as non-root user
+( cd $pkg_dir && $TAR $ogargs -X $tmp_dir/tarX --format=gnu --sort=name -cpf -  --mtime="$TIMESTAMP" . | $GZIP -n - > $tmp_dir/data.tar.gz )
+
+installed_size=`stat -c "%s" $tmp_dir/data.tar.gz`
+sed -i -e "s/^Installed-Size: .*/Installed-Size: $installed_size/" \
+	$pkg_dir/$CONTROL/control
+
+( cd $pkg_dir/$CONTROL && $TAR $ogargs --format=gnu --sort=name -cf -  --mtime="$TIMESTAMP" . | $GZIP -n - > $tmp_dir/control.tar.gz )
+rm $tmp_dir/tarX
 
 echo "2.0" > $tmp_dir/debian-binary
 
 pkg_file=$dest_dir/${pkg}_${version}_${arch}.ipk
-tar -C $tmp_dir -czf $pkg_file debian-binary data.tar.gz control.tar.gz
+rm -f $pkg_file
+( cd $tmp_dir && $TAR $ogargs --format=gnu --sort=name -cf -  --mtime="$TIMESTAMP" ./debian-binary ./data.tar.gz ./control.tar.gz | $GZIP -n - > $pkg_file )
+
 rm $tmp_dir/debian-binary $tmp_dir/data.tar.gz $tmp_dir/control.tar.gz
 rmdir $tmp_dir
 
